security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
            # for convenience, I decided to gather Sonata roles here
            ROLE_SONATA_MODERATOR_READER:
                - ROLE_SONATA_ADMIN_DEMO_MODERATOR_LIST
                - ROLE_SONATA_ADMIN_DEMO_MODERATOR_VIEW
            ROLE_SONATA_MODERATOR_EDITOR:
                - ROLE_SONATA_ADMIN_DEMO_MODERATOR_CREATE
                - ROLE_SONATA_ADMIN_DEMO_MODERATOR_EDIT
            ROLE_SONATA_MODERATOR_ADMIN:
                - ROLE_SONATA_ADMIN_DEMO_MODERATOR_DELETE
                - ROLE_SONATA_ADMIN_DEMO_MODERATOR_EXPORT

            ROLE_MODERATOR:   [ROLE_USER, ROLE_SONATA_MODERATOR_READER, ROLE_SONATA_MODERATOR_EDITOR]
            ROLE_ADMIN:       ROLE_USER
            ROLE_SUPER_ADMIN: ROLE_ADMIN

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory: ~

        fos_userbundle:
            #id: fos_user.user_provider.username #login whis user name
            id: fos_user.user_provider.username_email #login whis user email/name

    firewalls:
        main:
            pattern: ^/

            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                require_previous_session: false

                # submit the login form here
                check_path: /login_check

                # the user is redirected here when they need to log in
                login_path: /login

                # login success redirecting options (read further below)
                always_use_default_target_path: false
                default_target_path:            /profile/
                target_path_parameter:          _target_path
                use_referer:                    false

            logout:
                path:   /logout
                target: /
                invalidate_session: false
                delete_cookies:
                    a: { path: null, domain: null }
                    b: { path: null, domain: null }

            anonymous: true

            remember_me:
                secret: "%secret%"
                lifetime: 604800 # 1 week in seconds

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }

#instruction - http://symfony.com/doc/current/reference/configuration/security.html